### ISSUE TITLE
Volume Indicator Icon Doesn't Update When Clicking To Mute

### ISSUE THREAD

**Issue by belkinsa** [elementary/wingpanel-indicator-sound#130] opened 2019-12-22 16:31 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

When I click on the volume to change it and change it to mute. After clicking out of it, the icon doesn't update. This only happens when you click to change, not use the keyboard to change. It happens when you use speakers or headphones- no difference.

### To Reproduce
1. Go to Wing Panel
2. Click on Sound Indicator
3. Click to change the volume to mute
4. Click out
5. See error

### Screenshots or screen recordings

Before:

![BeforeChange](https://user-images.githubusercontent.com/8755311/71324587-91f6c700-24ae-11ea-9e70-e1800335a8a3.jpeg)

After:
![Screenshot from 2019-12-22 11-24-30](https://user-images.githubusercontent.com/8755311/71324550-09782680-24ae-11ea-920d-d4d3456be726.png)

## Platform Information

![Screenshot from 2019-12-22 11 26 52](https://user-images.githubusercontent.com/8755311/71324591-97541180-24ae-11ea-89bd-f8b566ed052b.jpeg)

- [x] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by kgrubb** [comment] 2020-04-15 20:13
@belkinsa, does this still happen with the latest release ([2.1.5](https://github.com/elementary/wingpanel-indicator-sound/releases/tag/2.1.5)) of wingpanel-indicator-sound?

**Comment by danrabbit** [comment] 2020-04-16 23:28
I can confirm this issue with the latest daily. You can reproduce this by moving the slider all the way down. It looks like there's probably two code paths for determining the icon somewhere in here

**Comment by danirabbit** [comment] 2023-02-14 20:58
This seems to actually be a duplicate of #180

**Closed by danirabbit** 2023-02-14 20:58 UTC
Labels: Status: Confirmed
