### ISSUE TITLE
[Enhancement] Big step size on scroll volume slider

### ISSUE THREAD

**Issue by varlesh** [elementary/wingpanel-indicator-sound#39] opened 2017-11-19 09:53 UTC
By default used 6% - it's very big and not comphortable:
`const double volume_step_percentage = 0.06`
That too much sound amplification.
Please change to **2%** by default or add option for change this on settings.

**Comment by peteruithoven** [comment] 2018-10-15 03:54
I'm afraid this wasn't simply caused by the stepsize, but by not properly handing smooth scrolling. 
Should be fixed with: https://github.com/elementary/wingpanel-indicator-sound/pull/74

**Closed** 2019-01-30 11:41 UTC
