### ISSUE TITLE
Dropdown width in sound indicator

### ISSUE THREAD

**Issue by mg-bizarre** [elementary/wingpanel-indicator-sound#171] opened 2020-11-02 14:55 UTC
While listening to spotify and switching between songs, the dropdown changes its width according to the song name (longer name - bigger width) and that makes the switch buttons move. For example, when I want to press the next button ">" several times, it moves which makes it very inconvenient. Could you set a fixed width for a music dropdown?

**Comment by danrabbit** [comment] 2020-11-03 20:19
Closing as a duplicate of #12

**Closed by danrabbit** 2020-11-03 20:19 UTC
