### ISSUE TITLE
Audio source switching from the wingpanel

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/wingpanel-indicator-sound#147] opened 2020-05-07 00:46 UTC
Currently you have to click into settings/sound then choose your sound source, which is quiet a process for a small task. Access from the top bar (panel) would be a nice to have feature
Thank you

**Comment by danrabbit** [comment] 2020-05-07 01:01
Closing as a duplicate of #87

**Closed by danrabbit** 2020-05-07 01:01 UTC
