### ISSUE TITLE
Should throttle notifications

### ISSUE THREAD

**Issue by peteruithoven** [elementary/wingpanel-indicator-sound#75] opened 2018-10-15 03:49 UTC
When scrolling over the indicator icon while the Popover is closed notifications are triggered for each adjustment. These add a huge lag to the volume adjusts. We should probably throttle those notifications. 

This might be the reason for: https://github.com/elementary/wingpanel-indicator-sound/issues/8

**Comment by danirabbit** [comment] 2023-12-30 17:01
I'm guessing this was fixed in #81 or similar? I can't reproduce a lag when scrolling no matter how fast I do it

**Closed by danirabbit** 2023-12-30 17:01 UTC
