### ISSUE TITLE
Scrolling behaviour of icon/popup contradicts system-settings behaviour.

### ISSUE THREAD

**Issue by JonnyCodewalker** [elementary/wingpanel-indicator-sound#45] opened 2018-01-05 23:11 UTC
If you use the mousewheel to scroll down you will reduce volume when hovering over the icon or over the popup-bar. However when scrolling down in the system settings it actually increases the volume. 
This inconsistency should be fixed. Possibly by changing the scrolling behaviour in the settings app so that scrolling down moves the bar to the left instead of the right (it also affects balance, though since that can't be changed elsewhere it feels less like a contradiction).

**Comment by peteruithoven** [comment] 2018-10-15 03:57
I think this is a duplicate of: #2 ?

**Comment by peteruithoven** [comment] 2019-02-06 20:07
With https://github.com/elementary/wingpanel-indicator-sound/pull/81 we've inverted how natural scrolling works so something we think is more intuitive for for example mouse pads. Ideally we wouldn't need to do this, which is why https://gitlab.gnome.org/GNOME/gtk/issues/1632 was opened. 
The non natural scrolling behavior is consistent with System Settings (or Scales in general). 
So how this currently works is by design, so I'm closing this issue.

**Closed by peteruithoven** 2019-02-06 20:07 UTC
