### ISSUE TITLE
Wingpanel Sound Indicator should use a different icon than Switchboard Sound Plug

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/wingpanel-indicator-sound#172] opened 2020-11-07 02:04 UTC
for reference see https://github.com/elementary/icons/issues/961 and https://github.com/elementary/switchboard-plug-sound/issues/170

**Comment by danrabbit** [comment] 2020-11-07 02:28
Since this is an AppCenter issue, this is a duplicate of https://github.com/elementary/appcenter/issues/1444

**Closed by danrabbit** 2020-11-07 02:28 UTC
