### ISSUE TITLE
Hide audio/video controls when no media is playing

### ISSUE THREAD

**Issue by waldyrious** [elementary/wingpanel-indicator-sound#35] opened 2017-10-24 10:43 UTC
I may be missing something, but I couldn't figure out a way to hide the controls from the music and video apps (Noise and Audience), even when they haven't been launched, and no video or audio is playing. This adds visual noise to the volume dialog and takes up unnecessary space:

![screenshot from 2017-10-24 11-37-15](https://user-images.githubusercontent.com/478237/31938854-8fe58652-b8b0-11e7-87bf-a975c907ef59.png)

I believe it would make sense for the indicator to hide these controls by default in such cases, but if that's not desirable, I'd like to at least have that option in the Sound settings dialog.

**Comment by chrisdotcode** [comment] 2017-11-30 19:03
What about if you want to preemptively adjust sound preferences *before* (or after) playing something?

**Comment by waldyrious** [comment] 2017-12-01 01:40
@chrisdotcode what do you mean? I'm only talking about the play / previous / next controls which are useless when no media is playing.

**Comment by chrisdotcode** [comment] 2017-12-01 05:17
@waldyrious My apologies, I mixed this up with another issue and was talking about something else.

**Comment by danrabbit** [comment] 2017-12-01 17:42
This is actually a feature and working as intended. The view point here is that Music is a service and can be started and stopped at any time, even if the app window is closed. Going to close this issue as "Opinion", but feel free to continue discussion if you feel strongly otherwise

**Closed by danrabbit** 2017-12-01 17:42 UTC

**Comment by waldyrious** [comment] 2017-12-02 18:41
Thanks for the clarification and the openness to further discussion. Indeed do feel strongly otherwise.

First, because those controls get in the way for the users who don't really play music on their computers. (For example, I only play occasional video or audio files, but very rarely reproduce entire playlists locally.) Yet everyone is forced to have a sizeable chunk of the area of the volume dialog occupied by controls that have no use to them most of the time. Couldn't the presence of media controls (when no media is playing) at least be something one could opt out of?

And second, because it's unclear what's supposed to happen if one just hits the play button when no songs are playing / the player hasn't been opened. Whatever is the intent, I don't think we can expect most users to guess it confidently, nor it seems, IMHO, like a use case worth keeping the controls permanently available (and here I'm referring to even the users who *do* play music using their computer).

I might be missing some angle into this, so please correct any misconceptions on my part.
