### ISSUE TITLE
List and allow selecting output devices if more than one connected

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-sound#26] opened 2017-07-01 22:25 UTC
If I connect an HDMI cable to a display with audio output (or have Bluetooth headphones connected), it could be handy to let me select the audio output device right in the indicator.

**Comment by danrabbit** [comment] 2017-07-03 17:09
Closing as a duplicate of #6 ;)

**Closed by danrabbit** 2017-07-03 17:09 UTC
