### ISSUE TITLE
spotify not showing album art properly

### ISSUE THREAD

**Issue by Jane2213** [elementary/wingpanel-indicator-sound#146] opened 2020-04-17 02:47 UTC
It seems like half the time music on spotify is playing the album artwork doesn't properly show up. It shows the default music icon.

**Comment by CCaroV** [comment] 2020-05-25 20:22
Same here, it used to show the album artwork before. Is this because of spotify or the wingpanel indicator?

**Comment by ryonakano** [comment] 2020-10-14 22:19
Thanks for your reporting, but I'm closing this as a duplicate of #145.

**Closed by ryonakano** 2020-10-14 22:19 UTC
