### ISSUE TITLE
Two Volume popups appear while changing volume

### ISSUE THREAD

**Issue by mridulganga** [elementary/wingpanel-indicator-sound#59] opened 2018-04-24 03:30 UTC
If the Sound popup has been opened by clicking and the keyboard is used to change the sound, then another popup for volume appears. Both change values simultaneously. See the screenshot.

![sound_bug](https://user-images.githubusercontent.com/3828236/39164619-e2dc3d48-479d-11e8-907d-8840747c42d3.png)

**Comment by danrabbit** [comment] 2018-04-24 03:36
Closing as a duplicate of #9

**Closed by danrabbit** 2018-04-24 03:36 UTC
