### ISSUE TITLE
Entry for default music player is not handled

### ISSUE THREAD

**Issue by nick87720z** [elementary/wingpanel-indicator-sound#162] opened 2020-10-09 20:44 UTC
Entry for default music player can't control runing player, nor can start it by play button.
When player i started (even by click on that default entry), new entry appears above default, and it only can be used for control.
Other (non-default) players have only one fully functional entry.

Tested at least these 3 players: noise, melody and pragha
(though noise will not work along with melody).

I use stable eOS distro with upgrades, with only stable elementary-specific archives (no elementary-daily).
Did not forget to search for other issues, nothing related about default player or double entries.

![Screenshot from 2020-10-10 01 19 46](https://user-images.githubusercontent.com/3896190/95629768-08929e80-0a9a-11eb-9a69-60608d3a14a2.png)
![Screenshot from 2020-10-10 01 22 57](https://user-images.githubusercontent.com/3896190/95629771-09c3cb80-0a9a-11eb-8609-6940a2d4ec36.png)
![Screenshot from 2020-10-10 01 25 35](https://user-images.githubusercontent.com/3896190/95629773-09c3cb80-0a9a-11eb-89e6-f60d265dc652.png)

**Comment by ryonakano** [comment] 2020-10-14 22:15
Thank you for your report, but I'm closing this issue as a duplicate of #157.

**Closed by ryonakano** 2020-10-14 22:15 UTC
